name = "AGAM"
default_targets = ["win64"]
build_directory = "build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "Steam/**",
]

[archive_files]
"steam_api64.dll" = "steam_api64.dll"
"Steam" = "Steam"


icon_file = "Sprites/Slime.png"