name = "AGAM"
default_targets = ["win64,appimage"]
build_directory = "build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "Steam/**",
]

[archive_files]
"steam_api64.dll" = "steam_api64.dll"
"libsteam_api.dylib" = "libsteam_api.dylib"
"libsteam_api.so" = "libsteam_api.so"
"Steam" = "Steam"


icon_file = "Sprites/Slime.png"